var annotated_dup =
[
    [ "CKAllocdMemory", "structCKAllocdMemory.html", "structCKAllocdMemory" ],
    [ "CKApp", "classCKApp.html", "classCKApp" ],
    [ "CKButton", "classCKButton.html", "classCKButton" ],
    [ "CKCanvas", "classCKCanvas.html", "classCKCanvas" ],
    [ "CKCheckbox", "classCKCheckbox.html", "classCKCheckbox" ],
    [ "CKColor", "structCKColor.html", "structCKColor" ],
    [ "CKControl", "classCKControl.html", "classCKControl" ],
    [ "CKControlInitParams", "structCKControlInitParams.html", "structCKControlInitParams" ],
    [ "CKControlToolbox", "classCKControlToolbox.html", "classCKControlToolbox" ],
    [ "CKDropdown", "classCKDropdown.html", "classCKDropdown" ],
    [ "CKEvent", "structCKEvent.html", "structCKEvent" ],
    [ "CKException", "classCKException.html", "classCKException" ],
    [ "CKFocusableControl", "classCKFocusableControl.html", "classCKFocusableControl" ],
    [ "CKLabel", "classCKLabel.html", "classCKLabel" ],
    [ "CKMenu", "classCKMenu.html", "classCKMenu" ],
    [ "CKMenuBar", "classCKMenuBar.html", "classCKMenuBar" ],
    [ "CKMenuItem", "classCKMenuItem.html", "classCKMenuItem" ],
    [ "CKNetBaseSocket", "classCKNetBaseSocket.html", "classCKNetBaseSocket" ],
    [ "CKNetBaseSocketEvtFromInterrupt", "structCKNetBaseSocketEvtFromInterrupt.html", "structCKNetBaseSocketEvtFromInterrupt" ],
    [ "CKNetBaseSocketNotifyEvt", "structCKNetBaseSocketNotifyEvt.html", "structCKNetBaseSocketNotifyEvt" ],
    [ "CKNetClient", "classCKNetClient.html", "classCKNetClient" ],
    [ "CKObject", "classCKObject.html", "classCKObject" ],
    [ "CKPoint", "structCKPoint.html", "structCKPoint" ],
    [ "CKProfilerData", "classCKProfilerData.html", "classCKProfilerData" ],
    [ "CKProperty", "classCKProperty.html", "classCKProperty" ],
    [ "CKRadiobox", "classCKRadiobox.html", "classCKRadiobox" ],
    [ "CKRect", "structCKRect.html", "structCKRect" ],
    [ "CKScopeProfiler", "classCKScopeProfiler.html", "classCKScopeProfiler" ],
    [ "CKSize", "structCKSize.html", "structCKSize" ],
    [ "CKTextableControl", "classCKTextableControl.html", "classCKTextableControl" ],
    [ "CKTextArea", "classCKTextArea.html", "classCKTextArea" ],
    [ "CKTextField", "classCKTextField.html", "classCKTextField" ],
    [ "CKTextFieldColors", "structCKTextFieldColors.html", "structCKTextFieldColors" ],
    [ "CKTimer", "classCKTimer.html", "classCKTimer" ],
    [ "CKValueContainingControl", "classCKValueContainingControl.html", "classCKValueContainingControl" ],
    [ "CKWindow", "classCKWindow.html", "classCKWindow" ],
    [ "CKWindowInitParams", "structCKWindowInitParams.html", "structCKWindowInitParams" ],
    [ "has_subscribe", "structhas__subscribe.html", null ],
    [ "has_subscribe< U, std::void_t< decltype(std::declval< U >().Subscribe(std::declval< std::function< void()> >()))> >", "structhas__subscribe_3_01U_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01U_01_4_07_08_8S08d8e9761e988ae3fead02cd3089b874.html", null ]
];